### ISSUE TITLE
Adding file of 'CONTRIBUTING.md' and LISTEN for the project

### ISSUE THREAD

**Issue by zhlhahaha** [imega-docker/jq#3]
Hi Irvis and Imega, we want to enable jq on ARM64 platform, but there is no 'CONTRIBUTING.md' and LISTEN here, so we are not able to contribute code here. Can you add the files?
Example：
https://github.com/hustcat/sriov-cni/blob/master/LICENSE
https://github.com/hustcat/sriov-cni/blob/master/CONTRIBUTING.md
Guideline:
https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors
https://help.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository

**Comment by zhlhahaha** [comment]
ping @irvis @iMega @lubinsz

**Comment by iMega** [comment]
@zhlhahaha could you please review the PR?

**Comment by zhlhahaha** [comment]
Looks good, thanks!
